---

- name: Lab 3 - Create nodes using bigip_node module and with_items
  hosts: bigip-a
  connection: local
  gather_facts: no


  vars:
    user: admin
    password: admin
    servers:
      - { name: Server1, address: "10.1.10.100", sessionState: "enabled" }
      - { name: Server2, address: "10.1.10.101", sessionState: "disabled"  }

  tasks:
     - name: Create nodes using with_items
       bigip_node:
          user: "{{ user }}"
          password: "{{ password }}"
          server: "{{ inventory_hostname }}"
          session_state: "{{ item.sessionState }}"
          validate_certs: no
          name: "{{ item.name }}"
          address: "{{ item.address }}"
       delegate_to: localhost
       with_items: "{{ servers }}"

