---

- name: Install latest HTTP iApp template 
  hosts: bigip-a
  connection: local
  gather_facts: no

  vars:
    userName: admin
    password: admin

  tasks:
       - name: Install HTTP iApp
         bigip_iapp_template:
           content: "{{ lookup('file', '/home/ubuntu/ansible/tmp/f5.http.v1.2.0.tmpl') }}"
           password: "{{ userName }}"
           server: "{{ inventory_hostname }}"
           state: present
           user: "{{ password }}"
           validate_certs: no
         delegate_to: localhost


